[package]
name = "ch16-concurrency"
version = "0.1.0"
authors = ["Sergio Alejandro Vargas <savargasqu+git@unal.edu.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
